theme: jekyll-theme-minimal
title: STA-371G
description: This is the course website for all sections of Prof. Jared Murray's fall 2017 Statistics and Modeling (STA-371G) course.
show_downloads: "false"