theme: jekyll-theme-minimal
title: Statistics and Modeling (STA-371G) Fall 2017
description: This is the course website for all sections of Prof. Jared Murray's fall 2017 Statistics and Modeling (STA-371G) course.
show_downloads: "false"
classyear: fall 2017